"""Initial migration

Revision ID: d23ad6977999
Revises: 
Create Date: 2024-06-24 16:21:16.659763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd23ad6977999'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer', sa.String(), nullable=True),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('length1', sa.Float(), nullable=True),
    sa.Column('length2', sa.Float(), nullable=True),
    sa.Column('length3', sa.Float(), nullable=True),
    sa.Column('width1', sa.Float(), nullable=True),
    sa.Column('width2', sa.Float(), nullable=True),
    sa.Column('width3', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_customer'), 'data', ['customer'], unique=False)
    op.create_index(op.f('ix_data_id'), 'data', ['id'], unique=False)
    op.create_index(op.f('ix_data_product'), 'data', ['product'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_product'), table_name='data')
    op.drop_index(op.f('ix_data_id'), table_name='data')
    op.drop_index(op.f('ix_data_customer'), table_name='data')
    op.drop_table('data')
    # ### end Alembic commands ###
